### ISSUE TITLE
Collapses nodes to 'abc' ? 

### ISSUE THREAD

**Issue by AndrewRayCode** [siefkenj/prettier-plugin-pegjs#3]
This line https://github.com/siefkenj/prettier-plugin-pegjs/blob/181102af3f757f54611a12d365f7a7132422b106/src/libs/printer.js#L261

Is for some reason triggering with this production:

```pegjs
switch_statement
  = switchSymbol:SWITCH
    l:LEFT_PAREN
    expr:expression
    r:RIGHT_PAREN
    body:(
      lb:LEFT_BRACE stmts:statement_list? rb:RIGHT_BRACE {
          return { lb, stmts, rb };
        }
    ) {
      const { lb, stmts rb } = body;
      return node(switchSymbol.name); }
```

When I format this, it collapses to

```
switch_statement = abc
```

**Comment by siefkenj** [comment]
It looks like your Javascript is invalid....try

```
switch_statement
  = switchSymbol:SWITCH
    l:LEFT_PAREN
    expr:expression
    r:RIGHT_PAREN
    body:(
      lb:LEFT_BRACE stmts:statement_list? rb:RIGHT_BRACE {
          return { lb, stmts, rb };
        }
    ) {
      const { lb, stmts, rb } = body;
      return node(switchSymbol.name); }
```

The lack of error is very misleading, though!

**Comment by siefkenj** [comment]
Should be fixed in https://github.com/siefkenj/prettier-plugin-pegjs/commit/c1136c95e393a970694bc1ce4b8671c892a93407  Now malformed Javascript is directly passed through.
